export const DEFAULT_GLOBAL_TYPEORM_SYNCHRONIZE = false;
export const DEFAULT_GLOBAL_TYPEORM_LOGGING = false;

export const GLOBAL_TYPEORM_TYPE_VARIABLE_NAME = 'GLOBAL_TYPEORM_TYPE';
export const GLOBAL_TYPEORM_HOST_VARIABLE_NAME = 'GLOBAL_TYPEORM_HOST';
export const GLOBAL_TYPEORM_PORT_VARIABLE_NAME = 'GLOBAL_TYPEORM_PORT';
export const GLOBAL_TYPEORM_USERNAME_VARIABLE_NAME = 'GLOBAL_TYPEORM_USERNAME';
export const GLOBAL_TYPEORM_PASSWORD_VARIABLE_NAME = 'GLOBAL_TYPEORM_PASSWORD';
export const GLOBAL_TYPEORM_DATABASE_VARIABLE_NAME = 'GLOBAL_TYPEORM_DATABASE';
export const GLOBAL_TYPEORM_SYNCHRONIZE_VARIABLE_NAME =
	'GLOBAL_TYPEORM_SYNCHRONIZE';
export const GLOBAL_TYPEORM_LOGGING_VARIABLE_NAME =
	'GLOBAL_TYPEORM_LOGGING';
