branch-defaults:
  default:
    environment: awsebdeployexample-dev
    group_suffix: null
environment-defaults:
  awsebdeployesample-env-1:
    branch: null
    repository: null
global:
  application_name: aws eb deploy example
  branch: null
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  # 여기 profile은 적절한것을 지정할것
  profile: eb-only
  repository: null
  sc: null
  workspace_type: Application
